---

- name: Настройка бэкапа на git-lab
  hosts: git-host
  become: yes

  handlers:
    - name: reconfigure gitlab
      become: true
      command: gitlab-ctl reconfigure
  
  tasks:

  # - name: Установить cifs
  #   apt:
  #     name:
  #       - cifs-utils

  # - name: Смонтировать сетевую папку для хранения бэкапов
  #   mount:
  #     src: '{{ share_backup }}'
  #     path: '{{ mountpoint_backup }}'
  #     fstype: cifs
  #     opts: 'username={{ mount_user }},password={{ mount_pass }}, mfsymlinks,uid=git'
  #     state: ephemeral

  - name: Сконфигурировать gitlab.rb - установить срок хранения бэкапов в 604800 сек (7 дней)
    tags:
    - reconfigure
    ansible.builtin.lineinfile:
      path: /etc/gitlab/gitlab.rb
      regexp: 'backup_keep_time'
      line: "gitlab_rails['backup_keep_time'] = 604800"
    notify: reconfigure gitlab

  - name: Сконфигурировать gitlab.rb - включить автоочистку бэкапов старше 604800 сек (7 дней)
    tags:
    - reconfigure
    ansible.builtin.lineinfile:
      path: /etc/gitlab/gitlab.rb
      regexp: 'manage_backup_path'
      line: "gitlab_rails['manage_backup_path'] = true"
    notify: reconfigure gitlab


  - name: Сконфигурировать gitlab.rb - изменить путь храннеия бэкапов
    tags:
    - reconfigure
    ansible.builtin.lineinfile:
      path: /etc/gitlab/gitlab.rb
      regexp: '[^_]backup_path'
      line: "gitlab_rails['backup_path'] = \"{{ x_backup }}\""
    notify: reconfigure gitlab


  # - name: Flush handlers
  #   meta: flush_handlers

  - name: Шаблон git_backup_weekly-1.sh
    template:
      src: ./templates/git_backup_weekly-1.sh.j2
      dest: /root/git_backup_weekly-1.sh

  - name: Шаблон gitlab_rb_backup_weekly-1.sh
    template:
      src: ./templates/gitlab_rb_backup_weekly-1.sh.j2
      dest: /root/gitlab_rb_backup_weekly-1.sh  

  - name: Шаблон gitlab_rb_backup_xdaily.sh
    template:
      src: ./templates/gitlab_rb_backup_xdaily.sh.j2
      dest: /root/gitlab_rb_backup_xdaily.sh 
  
  - name: Настройка расписания бэкапа файла gitlab.rb каждый день в 00:00
    cron:
      name: Start xdaily Script gitlab_rb backup
      job: '/root/gitlab_rb_backup_xdaily.sh'
      user: root
      minute: '00'
      hour: '00'
      day: '*'
      month: '*'
      weekday: '*'
    
  - name: Настройка расписания бэкапа файла gitlab.rb в первый день месяца в 00:05
    cron:
      name: Start Weekly Script gitlab_rb backup
      job: '/root/gitlab_rb_backup_weekly-1.sh'
      user: root
      minute: '05'
      hour: '00'
      day: '1'
      month: '*'
      weekday: '*'

  - name: Настройка расписания бэкапа GitLab каждый день в 00:10
    cron:
      name: Start xdaily Script gitlab backup
      job: '/opt/gitlab/bin/gitlab-rake COMPRESS_CMD=gzip -c --best gitlab:backup:create CRON=1'
      user: root
      minute: '10'
      hour: '00'
      day: '*'
      month: '*'
      weekday: '*'

  - name: Настройка расписания бэкапа GitLab в первый день месяца в 02:00
    cron:
      name: Start Weekly Script gitlab backup
      job: '/root/git_backup_weekly-1.sh'
      user: root
      minute: '00'
      hour: '02'
      day: '1'
      month: '*'
      weekday: '*'