---

- name: Настройка бэкапа на git-lab
  hosts: git-host
  become: yes

  handlers:
    - name: reconfigure gitlab
      become: true
      command: gitlab-ctl reconfigure
  
  tasks:

  # - name: Установить cifs
  #   apt:
  #     name:
  #       - cifs-utils

  # - name: Смонтировать сетевую папку для хранения бэкапов
  #   mount:
  #     src: '{{ share_backup }}'
  #     path: '{{ mountpoint_backup }}'
  #     fstype: cifs
  #     opts: 'username={{ mount_user }},password={{ mount_pass }}, mfsymlinks,uid=git'
  #     state: ephemeral

  - name: 
    debug:
    msg  "!vault |/n          $ANSIBLE_VAULT;1.1;AES256/n          62386237363839333166636134633631366131383235356334336461653837393261396161373965/n          6535343432613935326661363762306663663463313037390a643331656465636562333338616636/n          37343565613062643662313132656237396331333361366262396330613937623363643865633037/n          6339326264646433300a363764636638353364653562346366643431386135336631363836393338/n          3965"


  - name: Сконфигурировать gitlab.rb - установить срок хранения бэкапов 
    tags:
    - reconfigure
    ansible.builtin.lineinfile:
      path: /etc/gitlab/gitlab.rb
      regexp: 'backup_keep_time'
      line: "gitlab_rails['backup_keep_time'] = {{ keep_xdaily_backup }}"
    notify: reconfigure gitlab

  - name: Сконфигурировать gitlab.rb - включить автоочистку бэкапов 
    tags:
    - reconfigure
    ansible.builtin.lineinfile:
      path: /etc/gitlab/gitlab.rb
      regexp: 'manage_backup_path'
      line: "gitlab_rails['manage_backup_path'] = true"
    notify: reconfigure gitlab


  - name: Сконфигурировать gitlab.rb - изменить путь храннеия бэкапов
    tags:
    - reconfigure
    ansible.builtin.lineinfile:
      path: /etc/gitlab/gitlab.rb
      regexp: '[^_]backup_path'
      line: "gitlab_rails['backup_path'] = \"{{ x_backup }}\""
    notify: reconfigure gitlab


  - name: Flush handlers
    tags:
    - reconfigure  
    meta: flush_handlers

  - name: Шаблон git_backup_weekly-1.sh
    template:
      src: ./templates/git_backup_weekly-1.sh.j2
      dest: /root/git_backup_weekly-1.sh

  - name: Шаблон gitlab_rb_backup_weekly-1.sh
    template:
      src: ./templates/gitlab_rb_backup_weekly-1.sh.j2
      dest: /root/gitlab_rb_backup_weekly-1.sh  

  - name: Шаблон gitlab_rb_backup_xdaily.sh
    template:
      src: ./templates/gitlab_rb_backup_xdaily.sh.j2
      dest: /root/gitlab_rb_backup_xdaily.sh 
  
  - name: Настройка расписания бэкапа файла gitlab.rb каждый день 
    cron:
      name: Start xdaily Script gitlab_rb backup
      job: '/root/gitlab_rb_backup_xdaily.sh'
      user: root
      minute: "{{ backup_xday_gitlab_rb_min }}"
      hour: "{{ backup_xday_gitlab_rb_hour }}"
      day: '*'
      month: '*'
      weekday: '*'
    
  - name: Настройка расписания бэкапа файла gitlab.rb в первый день месяца 
    cron:
      name: Start Weekly Script gitlab_rb backup
      job: '/root/gitlab_rb_backup_weekly-1.sh'
      user: root
      minute: "{{ backup_month_gitlab_rb_min }}"
      hour: "{{ backup_month_gitlab_rb_hour }}"
      day: '1'
      month: '*'
      weekday: '*'

  - name: Настройка расписания бэкапа GitLab каждый день
    cron:
      name: Start xdaily Script gitlab backup
      job: '/opt/gitlab/bin/gitlab-rake COMPRESS_CMD=gzip -c --best gitlab:backup:create CRON=1'
      user: root
      minute: "{{ backup_xday_gitlab_min }}"
      hour: "{{ backup_xday_gitlab_hour }}"
      day: '*'
      month: '*'
      weekday: '*'

  - name: Настройка расписания бэкапа GitLab в первый день месяца
    cron:
      name: Start Weekly Script gitlab backup
      job: '/root/git_backup_weekly-1.sh'
      user: root
      minute: "{{ backup_month_gitlab_min }}"
      hour: "{{ backup_month_gitlab_hour }}"
      day: '1'
      month: '*'
      weekday: '*'